<a href="https://colab.research.google.com/github/ahmdbnrsl/Machine-Learning/blob/main/Algorithma/Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
# Dot Product Rule
A = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

B = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# Row × Column

print(A @ B, B @ A, A.shape, B.shape, (A@B).shape, (B@A).shape)

[[ 9 12 15]
 [19 26 33]
 [29 40 51]] [[22 28]
 [49 64]] (3, 2) (2, 3) (3, 3) (2, 2)


In [ ]:
import numpy as np
np.random.seed(42)

x_train = np.array([[0], [8], [15]], dtype=float)
y_train = np.array([[32], [46.4], [59]], dtype=float)

w = np.random.randn(1, 1)
b = np.random.randn(1)
lr = 0.001

N = x_train.shape[0]

for i in range(40000):
    y_pred = np.dot(x_train, w) + b
    error_diff = y_train - y_pred

    mse = np.mean(error_diff ** 2)
    dw = -2 * np.dot(x_train.T, error_diff) / N

    db = -2 * np.mean(error_diff)

    w = w - (lr * dw)
    b = b - (lr * db)

w, b

(array([[1.8]]), array([32.]))

In [ ]:

# AND LOGIC
import numpy as np
np.random.seed(42)

x_train = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

y_train = np.array([[0], [0], [0], [1]])

w = np.random.randn(2, 1)
b = np.random.randn()
learning_rate = 0.001

def sigmoid(z):
    return 1/(1 + np.exp(-z))

for i in range(500000):
    z = x_train @ w + b
    a = sigmoid(z)

    dw = (x_train.T @ (a - y_train)) / 4
    db = np.mean(a - y_train)

    w = w - (learning_rate * dw)
    b = b - (learning_rate * db)

def predict(x):
    return sigmoid(x @ w + b)

predict(np.array([[1, 1]]))
print(w, b)

[[6.00574388]
 [6.00573411]] -9.18590784955083



$$\boxed{\text{GRADIENT BACKWARD PROPAGATION XOR LOGIC}}$$

$$dw_1 = \frac{dE}{da_2}\cdot\frac{da_2}{dz_2}\cdot\frac{dz_2}{da_1}\cdot\frac{da_1}{dz_1}\cdot \frac{dz_1}{dw_1}$$

$$db_1 = \frac{dE}{da_2}\cdot\frac{da_2}{dz_2}\cdot\frac{dz_2}{da_1}\cdot\frac{da_1}{dz_1}\cdot \frac{dz_1}{dn_1}$$

$$dw_2 = \frac{dE}{da_2}\cdot\frac{da_2}{dz_2}\cdot\frac{dz_2}{dw_2}$$

$$db_2 = \frac{dE}{da_2}\cdot\frac{da_2}{dz_2}\cdot\frac{dz_2}{dw_2}$$

In [5]:
# XOR LOGIC
import numpy as np
np.random.seed(42)

x_train = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

y_train = np.array([[0], [1], [1], [0]])

def sigmoid(z):
    return 1/(1 + np.exp(-z))

w1 = np.random.randn(2, 2)
b1 = np.random.randn()

w2 = np.random.randn(2, 1)
b2 = np.random.randn()

learning_rate = 0.01

for i in range(50000):
    a1 = sigmoid(x_train @ w1 + b1)
    a2 = sigmoid(a1 @ w2 + b2)

    dw2 = (a1.T @ (a2 - y_train)) / 4
    db2 = np.mean(a2 - y_train)

    dz1 = ((a2 - y_train) @ w2.T) * (a1 * (1 - a1))
    dw1 = (x_train.T @ dz1)/ 4
    db1 = np.mean(dz1, axis=0)

    w1 = w1 - (learning_rate * dw1)
    w2 = w2 - (learning_rate * dw2)

    b1 = b1 - (learning_rate * db1)
    b2 = b2 - (learning_rate * db2)

def predict(x):
    a1 = sigmoid(x @ w1 + b1)
    a2 = sigmoid(a1 @ w2 + b2)

    return a2

predict(np.array([[1, 1]]))

array([[0.04583887]])