<a href="https://colab.research.google.com/github/ahmdbnrsl/Machine-Learning/blob/main/Mathematics-Requirements/Maths_For_ML/Matrix_Calculus.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

$\textbf{Matrix Calculus}$

$\text{1.1 Turunan Pertama}$

$\text{a. Turunan sebagai linearisasi}$

Di kalkulus satu variabel (skalar), turunan sering kali didefinisikan secara sederhana sebagai linierisasi dari sebuah fungsi.
Artinya, untuk perubahan $x$ yang sangat kecil, perubahan fungsinya bisa dihampiri dengan garis lurus: $$f(x) - f(x_0) \approx f'(x_0)(x - x_0)$$ Teks memberikan beberapa pilihan notasi untuk linierisasi ini, namun yang paling direkomendasikan (diutamakan) untuk kelas ini adalah:$$df = f'(x)dx$$Di sini, $dx$ dan $dy$ (atau $df$) dianggap sebagai angka yang "sangat kecil" (disebut infinitesimals dalam matematika).

$\text{b. Aturan Emas: Jangan Membagi dengan }dx!$

Ini adalah poin transisi yang sangat penting! Dalam kalkulus skalar, kita sering membagi $dy$ dengan $dx$ sehingga menjadi $\frac{dy}{dx}$. Namun, teks ini memberikan peringatan keras: jangan membagi dengan $dx$! Alasannya: Meskipun pembagian ini sah-sah saja untuk skalar, begitu kita masuk ke dunia vektor dan matriks, kita tidak selalu bisa membagi dengan sebuah vektor atau matriks. Oleh karena itu, kita mempertahankan bentuk perkalian $f'(x)dx$.

$\text{c. Perubahan "Bentuk" (Shape) dari Turunan}$

Saat kita meninggalkan dunia skalar dan memandang matriks secara holistik, konsep linierisasi tetap berlaku. Namun, turunan tidak lagi sekadar angka tunggal; turunan akan memiliki "bentuk" (shape) yang berbeda tergantung pada input dan outputnya.Teks memberikan tabel yang sangat penting untuk mengingat bentuk turunan:

- Input Skalar $\rightarrow$ Output Vektor = Turunannya berupa Vektor (contoh: kecepatan).
- Input Vektor $\rightarrow$ Output Skalar = Turunannya berupa Gradien (vektor kolom).
- Input Vektor $\rightarrow$ Output Vektor = Turunannya berupa Matriks (disebut Jacobian matrix).
- Input Matriks $\rightarrow$ Output Skalar = Turunannya berupa Matriks.

$\text{d. Pembuktian Konsep (Example 1)}$

Teks menutup bagian ini dengan sebuah contoh untuk membuktikan bahwa konsep diferensial sebagai linierisasi ini benar-benar bekerja.

Diberikan fungsi $f(x) = x^T x$, dengan input $x$ berupa vektor (matriks $2 \times 1$) dan output skalar (matriks $1 \times 1$). Titik awalnya adalah $x_0 = \begin{pmatrix} 3 \\ 4 \end{pmatrix}$.

- Nilai awal: $f(x_0) = 3^2 + 4^2 = 25$.
- Diberi gangguan kecil ($dx$): Misal $dx = \begin{pmatrix} 0.001 \\ 0.002 \end{pmatrix}$. Jika kita hitung nilai asli dari $f(x_0 + dx)$, hasilnya adalah $25.022005$.
- Menggunakan hampiran turunan: Teks menyatakan (dan akan dibuktikan nanti) bahwa diferensialnya adalah $2x_0^T dx$. Jika kita hitung nilainya: $2(3 \quad 4) \begin{pmatrix} 0.001 \\ 0.002 \end{pmatrix} = 0.022$.
- Kesimpulan: Selisih fungsinya $f(x_0 + dx) - f(x_0)$ adalah sekitar $0.022$, yang ternyata sangat cocok dengan hasil perhitungan diferensial kita ($2x_0^T dx = 0.022$). Ini membuktikan bahwa bentuk diferensial tersebut "tidak muncul begitu saja", melainkan benar-benar mewakili hampiran liniernya.

In [ ]:
import sympy as sp

def f(x: sp.matrices.dense.MutableDenseMatrix) -> float:
    return x.dot(x)

x_0 = sp.Matrix([3, 4])

dx = sp.Matrix([0.001, 0.002])

print(f(x_0 + dx) - f(x_0),
      2*x_0.dot(dx),
      f(x_0 + dx) - f(x_0),
      2*x_0.transpose().dot(x_0 + dx - x_0))

0.0220050000000001 0.0220000000000000 0.0220050000000001 0.0219999999999976


$\text{1.2 Perkalian Matriks}$

Tidak sama seperti perkalian skalar dan vektor, dimana dalam perkalian tersebut kita bisa terapkan sifat komutatif atau diubah urutannya, dalam matrix multiplication perubahan posisi perkalian akan mengubah hasilnya

In [ ]:
import numpy as np
a, b = np.array([1, 2]), np.array([3, 4])
a.T, b

(array([1, 2]), array([3, 4]))

Perkalian vektor kolom dan veektor baris, akan menghasilkan matrriks, jadi kita tidak di perbolehkan mengubah urutan perkaliannya.

In [ ]:
import sympy as sp
a = sp.Matrix([1, 2])
b = sp.Matrix([2, 4]).transpose()

a @ b, b @ a

(Matrix([
 [2, 4],
 [4, 8]]),
 Matrix([[10]]))

In [ ]:
import numpy as np
A = np.array([[1, 2], [2, 2]])
B = np.array([[2, 4], [1, 3]])

A @ B, B @ A

(array([[ 4, 10],
        [ 6, 14]]),
 array([[10, 12],
        [ 7,  8]]))

$\text{Perbedaan}\ \delta x \text{ dan }dx$

- $\delta x$ ini adalah perubahan fisik nyata, misal dari $x = 1$ ke $x = 1.00002$ maka $\delta x = 0.00002$
- $dx$ adalah infinitesimal, dimana ini adalah ukuran anak tangga perubahan $x$ yang sangat kecil mendekati $0$ tapi bukan $0$. Atau dalam kata lain anggap saja sebuah kurva dari fungsi kita pecah menjadi bagian atau persegi panjang yang lebar nya sangat kecil, lebar itulah yang kita sebut $dx$ dan tingginya adalah $f(x)$.

"Transpose itu hanya mengikuti" artinya jika fungsi di transpose maka turunannya juga di transpose, dan sebaliknya.